name: CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x ./gradlew

      - name: Gradle build & test
        working-directory: backend
        run: ./gradlew clean test